name: Build

on:
  pull_request:
    branches:
      - master
    paths:
      - 'powertools-core/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-parameters/**'
      - 'pom.xml'
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - 'powertools-core/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [8, 8.0.192, 11.0.x, 11.0.3, 12, 13 ]
    name: Java ${{ matrix.java }}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  auto-merge:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
          github-token: ${{ secrets.AUTOMERGE }}
