name: Validate IaC

on:
  pull_request:
    branches:
      - main
      - v2
    paths:
      - 'examples/**'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # v3.5.3
      - name: Setup java JDK 1.8
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: 'corretto'
          java-version: 8
      - name: Run SAM validator to check syntax of IaC templates
        working-directory: examples/powertools-examples-core/sam
        run: | 
          sam build
          sam validate --lint
