name: Publish package to the Maven Central Repository
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Publish package
        run: mvn -P sign,build-extras clean deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
